apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
      - name: platformservice
        image: subhra2023/platformservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        